### ISSUE TITLE
can you share blog post asap

### ISSUE THREAD

**Issue by Sandy4321** [bprabhakar/upside-down-reinforcement-learning#1]
can you share blog post asap
also see this
https://medium.com/@jscriptcoder/demystifying-upside-down-reinforcement-learning-a-k-a-%EA%93%A4-b7bd4214b33f
https://github.com/jscriptcoder/Upside-Down-Reinforcement-Learning

**Comment by bprabhakar** [comment]
Here's the blog post:
https://towardsdatascience.com/is-upside-down-reinforcement-learning-imitation-learning-4a9d346f9f98
